---
- hosts: jumpbox
  gather_facts: true
  roles:
    - role: osp_network
    - role: osp_keypairs
    - role: osp_custom_flavor
    - role: secgroups
  tasks:
##Create Fronend Instance
  - name: Create frontend instance
    include_role:
       name: servers
       vars_from: frontend.yml
###Create App1 server 
  - name: Create app1 instance
    include_role:
       name: servers
       vars_from: app1.yml
##Create App2 server
  - name: Create app2 instance
    include_role:
       name: servers
       vars_from: app2.yml
##Create DB server
  - name: Create db instance
    include_role:
       name: servers
       vars_from: db.yml
