---
- name: install Domain Services
  win_feature:
    name: AD-Domain-Services
    state: present

- name: set up the AD controller
  win_domain:
    dns_domain_name: "{{ ad_domain_name }}"
    safe_mode_password: "{{ ad_safe_mode_password }}"
  register: ad_result

- name: reboot
  win_reboot:
  when: ad_result.reboot_required

- name: display the domain list
  win_command: nltest /dclist:"{{ ad_domain_name }}"
